package net.namandixit.java.yamak;

enum TokenType {
    // Single-character tokens
    LPAREN, RPAREN, LBRACE, RBRACE,
    COMMA, DOT,
    SEMICOLON,
    MINUS, PLUS, SLASH, ASTERISK,
    // One or two character tokens
    EQUAL, EQUAL_EQUAL,
    LBRACKET, LBRACKET_EQUAL, LBRACKET_LBRACKET, LBRACKET_RBRACKET,
    RBRACKET, RBRACKET_EQUAL, RBRACKET_RBRACKET, RBRACKET_LBRACKET,
    COLON, COLON_EQUAL, COLON_COLON,
    // Literals
    IDENTIFIER, STRING, NUMBER,
    // Keywords
    WITH, RETURN, DEFER, IF, ELSE, MATCH, WHILE, BREAK, CONTINUE,
    LABEL, TYPE, FUNC, VAR, LET, STRUCT, UNION, TAGGED, ENUM, COLLECT,
    TRUE, FALSE,
    AND, OR, NOT,
    // Compile-time keywords (!if, etc.)
    COMPTIME_IF, COMPTIME_THEN, COMPTIME_ELSE, COMPTIME_END,
    COMPTIME_CAST_VAL, COMPTIME_CAST_MEM,
    COMMENT_LINE, COMMENT_BLOCK,
    EOF
}
